# Generated by Django 3.1.5 on 2021-10-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0002_auto_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='show_date',
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Hall name'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Hall size'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mycinema.cinemahall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Ticket price'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tickets', to='mycinema.session', verbose_name='Session'),
        ),
    ]
